# Generated by Django 4.1.4 on 2023-03-10 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='exercise_name',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='weight',
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sets', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('weight', models.CharField(max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='api.plan')),
            ],
        ),
    ]
