# Generated by Django 4.1.4 on 2023-03-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_plan_exercise_name_remove_plan_reps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='plan',
        ),
        migrations.AddField(
            model_name='plan',
            name='exercises',
            field=models.ManyToManyField(to='api.exercise'),
        ),
    ]
